// examples/react/with-hovercards.tsx
/**
 * React hovercards + themes example — <RenderedMessage /> (v0.2.0+).
 *
 * Shows:
 *  - Rendering a stored `@{userId}` message with styled mention chips
 *  - `hovercard` — reveal a profile card (avatar, meta, email, details) on hover
 *  - Copyable fields + a "copy user" button (copyUser as a custom function)
 *  - Theming with a `light` / `dark` preset via the `theme` prop
 *  - Enriching MentionUser with `email` and `details[]`
 */

import { useMemo, useState } from 'react';
import {
  RenderedMessage,
  type HovercardOptions,
  type MentionUser,
} from '@cursortag/mention-kit/react';

// ── Sample data ───────────────────────────────────────────────────────────────

const USERS: MentionUser[] = [
  {
    id: 'u1',
    name: 'Alice Johnson',
    meta: 'Staff Engineer · Engineering',
    color: '#7c3aed',
    email: 'alice@acme.com',
    details: [
      { label: 'Team', value: 'Platform' },
      { label: 'Slack', value: '@alice', href: 'https://slack.com' },
    ],
  },
  {
    id: 'u2',
    name: 'Bob Smith',
    meta: 'Product Designer · Design',
    color: '#0891b2',
    email: 'bob@acme.com',
    details: [{ label: 'Team', value: 'Design Systems' }],
  },
  {
    id: 'u3',
    name: 'Carol White',
    meta: 'PM · Product',
    color: '#059669',
    email: 'carol@acme.com',
  },
];

// A message as it would come back from your database.
const STORED =
  'Nice work @{u1}! Can you sync with @{u2} on the new tokens, ' +
  'and loop in @{u3} for the rollout plan?';

// ── Component ─────────────────────────────────────────────────────────────────

export function HovercardsExample() {
  const [dark, setDark] = useState(false);

  // Memoize object props so the hovercard isn't re-attached on every render.
  const hovercard = useMemo<HovercardOptions>(
    () => ({
      copyFields: true,
      copyUser: (u) => `${u.name} <${u.email ?? ''}>`.trim(),
    }),
    [],
  );

  return (
    <div
      style={{ maxWidth: 600, margin: '2rem auto', fontFamily: 'sans-serif' }}
    >
      <h2>@cursortag/mention-kit · React hovercards + themes</h2>

      <div
        style={{
          display: 'flex',
          gap: 8,
          alignItems: 'center',
          marginBottom: 12,
        }}
      >
        <button onClick={() => setDark((d) => !d)} aria-pressed={dark}>
          {dark ? '☀️ Light theme' : '🌙 Dark theme'}
        </button>
        <span style={{ fontSize: 12, color: '#6b7280' }}>
          hover a mention → profile card with copyable fields
        </span>
      </div>

      {/* A read-only rendered comment. Hover any chip to open its card. */}
      <div
        style={{
          border: '1px solid',
          borderColor: dark ? '#1e293b' : '#d1d5db',
          borderRadius: 8,
          padding: '12px 14px',
          lineHeight: 1.7,
          fontSize: 14,
          background: dark ? '#0b1220' : '#fff',
          color: dark ? '#e2e8f0' : '#111827',
        }}
      >
        <RenderedMessage
          message={STORED}
          users={USERS}
          hovercard={hovercard}
          theme={{ preset: dark ? 'dark' : 'light' }}
        />
      </div>

      <p style={{ fontSize: 12, color: '#6b7280', marginTop: 8 }}>
        The card, chips, copy buttons and links all restyle from{' '}
        <code>--mk-*</code> CSS variables — set them in your own CSS, or pass a{' '}
        <code>theme</code> object as shown above.
      </p>
    </div>
  );
}

// examples/vue/with-hovercards.vue
<script setup lang="ts">
/**
 * Vue hovercards + themes example — renderCommentMessage + attachHovercards (v0.2.0+).
 *
 * Shows:
 *  - Rendering a stored `@{userId}` message into your own container
 *  - `attachHovercards(root, users, opts)` — profile card on hover; returns a cleanup fn
 *  - Copyable fields + a "copy user" button
 *  - Theming chips (container `--mk-*` vars via applyTheme) and the card (opts.theme)
 *  - Proper cleanup on unmount and on theme change
 *
 * (Vue has no <RenderedMessage> component — you own the container, so you call
 *  renderCommentMessage + attachHovercards yourself. React ships the component.)
 */

import { onMounted, onUnmounted, ref, watch } from 'vue';
import {
  renderCommentMessage,
  attachHovercards,
  applyTheme,
  type MentionTheme,
  type MentionUser,
} from '@cursortag/mention-kit/vue';

// ── Sample data ───────────────────────────────────────────────────────────────

const users: MentionUser[] = [
  {
    id: 'u1',
    name: 'Alice Johnson',
    meta: 'Staff Engineer · Engineering',
    color: '#7c3aed',
    email: 'alice@acme.com',
    details: [
      { label: 'Team', value: 'Platform' },
      { label: 'Slack', value: '@alice', href: 'https://slack.com' },
    ],
  },
  {
    id: 'u2',
    name: 'Bob Smith',
    meta: 'Product Designer · Design',
    color: '#0891b2',
    email: 'bob@acme.com',
    details: [{ label: 'Team', value: 'Design Systems' }],
  },
  {
    id: 'u3',
    name: 'Carol White',
    meta: 'PM · Product',
    color: '#059669',
    email: 'carol@acme.com',
  },
];

const STORED =
  'Nice work @{u1}! Can you sync with @{u2} on the new tokens, ' +
  'and loop in @{u3} for the rollout plan?';

// ── State ─────────────────────────────────────────────────────────────────────

const surface = ref<HTMLElement | null>(null);
const dark = ref(false);
let cleanup: (() => void) | null = null;

// Render the stored message and (re)wire hovercards for the current theme.
function render() {
  const host = surface.value;
  if (!host) return;

  cleanup?.(); // tear down the previous card + listeners
  host.innerHTML = '';

  const theme: MentionTheme = { preset: dark.value ? 'dark' : 'light' };
  applyTheme(host, theme); // chips inherit --mk-* from the container

  for (const part of renderCommentMessage(STORED, users)) {
    host.appendChild(
      typeof part === 'string' ? document.createTextNode(part) : part,
    );
  }

  cleanup = attachHovercards(host, users, {
    theme,
    copyFields: true,
    copyUser: (u) => `${u.name} <${u.email ?? ''}>`.trim(),
  });
}

onMounted(render);
watch(dark, render);
onUnmounted(() => cleanup?.());
</script>

<template>
  <div class="example">
    <h2>@cursortag/mention-kit · Vue hovercards + themes</h2>

    <div class="controls">
      <button :aria-pressed="dark" @click="dark = !dark">
        {{ dark ? '☀️ Light theme' : '🌙 Dark theme' }}
      </button>
      <span class="hint"
        >hover a mention → profile card with copyable fields</span
      >
    </div>

    <!-- You own this container; the library renders chips + a floating card. -->
    <div ref="surface" class="surface" :class="{ dark }" />

    <p class="hint">
      Chips, the card, copy buttons and links all restyle from
      <code>--mk-*</code> CSS variables.
    </p>
  </div>
</template>

<style scoped>
.example {
  max-width: 600px;
  margin: 2rem auto;
  font-family: sans-serif;
}

.controls {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 12px;
}

.hint {
  font-size: 12px;
  color: #6b7280;
}

.surface {
  border: 1px solid #d1d5db;
  border-radius: 8px;
  padding: 12px 14px;
  line-height: 1.7;
  font-size: 14px;
}

.surface.dark {
  background: #0b1220;
  color: #e2e8f0;
  border-color: #1e293b;
}

code {
  font-family: monospace;
  background: #f3f4f6;
  padding: 2px 6px;
  border-radius: 4px;
}
</style>
